"""empty message

Revision ID: 4ce3929bfadb
Revises: f81a7e54e715
Create Date: 2023-02-08 22:04:24.041977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ce3929bfadb'
down_revision = 'f81a7e54e715'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pets', schema=None) as batch_op:
        batch_op.drop_column('pet_gender')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pet_gender', sa.VARCHAR(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
