"""empty message

Revision ID: c84ce1f92ac0
Revises: 4ce3929bfadb
Create Date: 2023-02-08 22:06:17.196697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c84ce1f92ac0'
down_revision = '4ce3929bfadb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pet_gender', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pets', schema=None) as batch_op:
        batch_op.drop_column('pet_gender')

    # ### end Alembic commands ###
